### ISSUE TITLE
Double quotes to single quotes conversion creates syntax error

### ISSUE THREAD

**Issue by MurkyMeow** [coderaiser/putout#192]
```js
// index.js
const putout = require("putout");

const out = putout(`
import React from "react";

export function MyComponent(props) {
	return (
		<button title={"Reach out to us, and we'll discuss your specific moving needs to provide tailored solutions."} />
	);
}
`);

console.log(out);
```

```sh
node index.js
```

Outputs this code:

```jsx
import React from 'react';

export function MyComponent(props) {
    return (
        <button title={'Reach out to us, and we'll discuss your specific moving needs to provide tailored solutions.'}/>
    );
}
```

Which is obviously broken as it now has an unmatched single quote

**Comment by MurkyMeow** [comment]
I'm using the eslint plugin and i don't get how to configure the putout's printer in this case. Creating a `putout.json` doesn't help.

**Comment by coderaiser** [comment]
Just fixed in [@putout/printer@6.3.0](https://github.com/putoutjs/printer/releases/tag/v6.3.0) 🎉 . Please re-install 🐊**Putout**. Is it works for you?

**Comment by gggscript** [comment]
@coderaiser, I think this problem still exists.

POC for `putout` CLI tool / putout's astexplorer website:
Tested with Putout version: `33.12.0` (CLI tool) and `33.10.0` (website)
```js
alert("This is text \\' but this will be code")
// ->
alert('This is text \\' but this will be code');
```
https://putout.cloudcmd.io/#/gist/fa19342acc9f7fb0fea2d266e42c31e2/ca2fa2781c5dfac46ed9bf8ace4d63444e9db97b

POC for `@putout/printer` package:
Tested with version `6.4.1`
```js
const printer = require('@putout/printer')
const { parse } = require('@babel/parser')

const input = `alert("'")`
alert({ actual: printer.print(parse(input)) })
// -> { actual: "alert(''');\n" }
```
