### ISSUE TITLE
TypeError: Cannot read property 'raw' of undefined

### ISSUE THREAD

**Issue by EvgenyOrekhov** [coderaiser/putout#67]
Looks like @putout/plugin-regexp can't handle named capturing groups.

```js
const regexp = /(?<foo>a)/;
```

gives the following error:

```text
TypeError: Cannot read property 'raw' of undefined
Occurred while linting /home/user/example.js:1
    at RegExpLiteral (/home/user/node_modules/@putout/plugin-regexp/lib/remove-useless-group/index.js:14:38)
```

ESLint: 7.30.0
putout: 18.4.0
eslint-plugin-putout: 8.1.0
@putout/plugin-regexp: 2.3.3

**Comment by coderaiser** [comment]
Thanks a lot :)! Fixed with 1c70b02. Landed in `@putout/plugin-regexp@2.3.4` 🎉 .

Is it works for you?

**Comment by EvgenyOrekhov** [comment]
No, still getting the same error with `@putout/plugin-regexp@2.3.4` :(

**Comment by coderaiser** [comment]
Fixed with https://github.com/coderaiser/estree-to-babel/commit/1d68886b4a6a45a3c362303b8aaa7c93a9f7f99c, landed in [estree-to-babel v4.0.2](https://github.com/coderaiser/estree-to-babel/commit/1d68886b4a6a45a3c362303b8aaa7c93a9f7f99c) 🎉 .

Is it works for you?

**Comment by EvgenyOrekhov** [comment]
The original error was fixed, but I started getting a totally different error:

```js
function foo({ bar }) {
  return { bar };
}

foo({ bar: 123 }); // "bar" is useless argument of a function "foo" (remove-useless-arguments/destructuring)
```

**Comment by EvgenyOrekhov** [comment]
Sorry, not an error, but a false positive.

**Comment by coderaiser** [comment]
> The original error was fixed, but I started getting a totally different error:
> 
> ```js
> function foo({ bar }) {
>   return { bar };
> }
> 
> foo({ bar: 123 }); // "bar" is useless argument of a function "foo" (remove-useless-arguments/destructuring)
> ```

I can’t reproduce this, just added this example like a test case.

**Comment by EvgenyOrekhov** [comment]
It happens only with ESM. I reproduced it here: https://github.com/EvgenyOrekhov/eslint-config-hardcore/pull/319.

**Comment by coderaiser** [comment]
> It happens only with ESM. I reproduced it here: [EvgenyOrekhov/eslint-config-hardcore#319](https://github.com/EvgenyOrekhov/eslint-config-hardcore/pull/319).

Fixed with 54e1145, landed in `@putout/compare@7.6.1` 🎉 . Is it works for you?

**Comment by EvgenyOrekhov** [comment]
It works now, thank you!
